apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  labels:
    app: mongo-db-ss
    tier: storage
spec:
  type: ClusterIP
  selector:
    app: mongo-db-ss
  ports:
  - port: 27017
    targetPort: 27017
