apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db-ss
spec:
  selector:
    matchLabels:
      app: mongo-db-ss
  serviceName: mongo-db-ss
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db-ss
        tier: storage
    spec:
      containers:
      - name: mongo-db-ss
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
          - name: mongo-config
            mountPath: /config
          - name: mongo-credentials
            mountPath: /etc/mongo-credentials
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim 
      - name: mongo-config
        configMap:
          name: mongo-config
          items:
          - key: mongo.conf
            path: mongo.conf
      - name: mongo-credentials
        secret:
          secretName: mongo-secret
  
